# Fetching A-Share Stock Universe
- A-Share data fetch often experience connection or data restrictions.
- This notebook shows several alternatives to fetch A-Share ticker universe.

## Option 1: akshare.stock_zh_a_spot_em fails with connection error.

In [18]:
# import akshare as ak
# stock_list = ak.stock_zh_a_spot_em()
# stock_list

## Option 2: adata_stock.info.all_code() works. This command takes approx 5 min.

In [5]:
from adata import stock as adata_stock
all_stocks_adata = adata_stock.info.all_code()
all_stocks_adata.to_csv("./all_stocks_adata.csv", index=False, encoding="utf-8-sig")
all_stocks_adata.head()

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

  stock_code short_name exchange   list_date
0     000001       平安银行       SZ  1991-04-03
1     000002        万科Ａ       SZ  1991-01-29
2     000004      *ST国华       SZ  1990-12-01
3     000006       深振业Ａ       SZ  1992-04-27
4     000007        全新好       SZ  1992-04-13

## Option 3: akshare.stock_info_a_code_name() works. This command takes approx 2 min.

In [7]:
import akshare as ak
all_stocks_akshare = ak.stock_info_a_code_name()
all_stocks_akshare.to_csv("./all_stocks.csv", index=False, encoding="utf-8-sig")
all_stocks_akshare.head()

  0%|          | 0/15 [00:00<?, ?it/s]

     code   name
0  000001   平安银行
1  000002  万  科Ａ
2  000004  *ST国华
3  000006   深振业Ａ
4  000007    全新好

## akshare has more accurate data than adata
- adata included delisted tickers
- adata is missing 200+ active tickers

In [11]:
len(all_stocks_akshare)

5485

In [13]:
len(all_stocks_adata)

5220

## Conclusion: Use akshare.stock_info_a_code_name()